# Generated by Django 2.2.4 on 2020-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20200217_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.ManyToManyField(to='App1.Category'),
        ),
    ]
