# Generated by Django 2.2.4 on 2020-02-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_institution_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokenResetPassword',
            field=models.TextField(default='test'),
        ),
    ]
