# Generated by Django 2.2.4 on 2020-02-21 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_user_tokenresetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tokenResetPassword',
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
