# Generated by Django 2.2.4 on 2020-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20200221_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
