# Generated by Django 2.2.4 on 2020-02-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_auto_20200221_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='unique_id',
            new_name='tokenResetPassword',
        ),
    ]
