# Generated by Django 2.2.4 on 2020-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_auto_20200221_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
