# Generated by Django 2.2.4 on 2020-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_donation_is_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField(null=True)),
                ('second', models.TextField(null=True)),
            ],
        ),
    ]
